name: AutoSitemap
on:
  push:
    branches:
      - master
jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate sitemap
        uses: cemreefe/AutoSitemap@v0.4.0
        with:
          path: .
